ntt-developers/ntt-tech-conference

.travis.yml, README.md
=> Travis CIを設定 ( related to #5 )

index.html, src/slim/index.slim
#9 のPRにindex.htmlの追加、タイムテーブルにスピーカー情報を追加。
=> Add whole timetable

README.md, package.json
npm-scriptsを追加
- `npm install` 後に自動で `bower install` されるようにした
- `npm run develop` でローカルwebサーバ起動
- `npm run build` でソースのビルドのみ実行
あわせて README も修正
=> npm-scriptsを追加

.travis.yml
changed `.travis.yml` to use `npm install` and `npm run build`.
=> use npm-scrpit in CI

.gitignore, index.html, src/slim/unconference.slim, unconference.html
=> Add unconference description

.travis.yml, index.html
アップロードされたhtmlとtravisがビルドしたhtmlが一致しないとコケるようになった。
=> check diff between included html and built html

for-beginners.html, index.html, src/slim/for-beginners.slim
=> Add Room302(for Beginners) descriptions

src/slim/for-beginners.slim
Please consider changing the description related to my session
=> Update PostgreSQL 10 session detail

src/slim/index.slim
懇親会の情報を追加しました。
[NTT Tech Conference #1 After Party - connpass](https://connpass.com/event/48110/)
=> Add after party information

src/slim/conference.slim, src/slim/for-beginners.slim, src/slim/timetable.slim, src/slim/unconference.slim
=> 全体テーブルに戻る際にも自動スクロールするようにした

src/slim/index.slim
=> Add contributor description

src/slim/showcase.slim
見た目は全く変わってないけど、slimのお手本として使われそうなので
- pタグはちゃんとparagraphを表すようにする。
- 改行を意図している場合はbrを使う
という感じにリファクタリング。
=> minor fix of DOM

src/slim/index.slim, src/slim/showcase.slim
#61 
`col-md-8` は「2/3を埋める横幅」っていうclassだけど `row` で指定しないと横に並べられてしまう気がする。
なおこのコミットで直った確証が無いのでプレビューで判断したい。
=> `row` should be specified explicitly

README.md
README Preview: https://github.com/ntt-developers/ntt-tech-conference-01/tree/add-status
=> Add Travis CI build status.

src/slim/timetable.slim
Update the organization of timetable to fix #74 completely.
=> Update timetable to fix the organization as #74

.travis.yml
=> 外のリポジトリからpull-req送るとtravisが絶対コケる

src/slim/conference.slim, src/slim/index.slim, src/slim/timetable.slim
OpeningとClosingのSlideを一部編集して公開しましたのでリンク追加しました
=> Add Opening & Closing Keynote slides

src/slim/for-beginners.slim, src/slim/timetable.slim
=> Added links to the Hojo's slide.

02/package-lock.json, 02/src/slim/timetable.slim
講演者の所属は各セッションの詳細の方に記載することにして、表示量削減によるみやすさを取ってみた。
=> タイムテーブルを#2用に変更

02/src/slim/conference1.slim, 02/src/slim/conference2.slim, 02/src/slim/index.slim, 02/src/slim/timetable.slim
* うまく動作しないリンクを修正した
* ラベルについて、confXXという通し番号はやめて、conf1-X, conf3-X, というようにした
=> Fix labels to jump from index page to room 303 page.

02/src/slim/index.slim
=> Add registration contents

02/gulpfile.coffee, 02/package.json, 02/yarn.lock
scss and font files are not in fontawesome, so use font-awesome instead.
=> Use font-awesome instead of fontawesome to fix icon.

01/assets/javascripts/application.min.js, 02/assets/javascripts/application.min.js
#92 added assets directory to .gitignore but we forgot to delete files in the directory. Remove them.
=> Remove remaining files in assets directory.

deploy.sh
https://ntt-developers.github.io/ntt-tech-conference/ is File not found(404)
This PR add README.md to top directory at gh-pages branch
close #111
=> Fix Top page

02/src/scss/mplus1p.scss, 02/src/scss/style.scss
読みやすいようにMplusのWebフォントを使用
[Google Fonts + 日本語 早期アクセス • Google Fonts + Japanese Early Access](https://googlefonts.github.io/japanese/)
=> Use Mplus web font

02/src/slim/conference1.slim
一人でやることにしたので、記述を修正。
ユーザ会云々の記述を削除し、代わりにアジェンダを追記
=> セッション内容の記述を修正

02/src/slim/conference2.slim, 02/src/slim/timetable.slim
E2D3の開発で気づいたOSSの効用 に関する情報を更新しました。よろしくお願いいたします。:bow:
=> update 2 files(conference2.slim and timetable.slim)

02/src/slim/conference1.slim, 02/src/slim/conference2.slim, 02/src/slim/index.slim, 02/src/slim/timetable.slim
現在公開されている資料全部を掲載しました。
close: #141 の分も回収済み
=> Add links of presentation materials

02/src/slim/conference1.slim, 02/src/slim/index.slim, 02/src/slim/timetable.slim, 02/src/slim/unconference.slim
=> Add links of UI/UX and StackStorm

02/src/slim/conference1.slim, 02/src/slim/timetable.slim
・鈴木さんの資料のリンクを追記
・Keynoteに喋った人の名前を追記
=> Add link of god's slides

.travis.yml
やったこと
* NTT Tech Conference 3のイベントページデプロイ用にTravisの設定ファイルにスクリプトを追記
=> Change .travis.yml to deploy event pages of #3

03/src/slim/_schedule.slim, 03/src/slim/_workshop.slim, 03/src/slim/index.slim
やったこと
* Schedule（本編）のタイムテーブルの記載
* Workshop（午前）のタイムテーブルの記載
=> Add schedule of NTT Tech Conference #3

03/src/slim/index.slim
=> index.slimにshowcaseのモーダルをinclude

03/src/scss/bootstrap.scss, 03/src/slim/_conference_modal.slim, 03/src/slim/_schedule.slim, 03/src/slim/_showcase_modal.slim, 03/src/slim/_workshop_modal.slim, 03/src/slim/index.slim
=> Add descriptions to Time Table

03/src/slim/_conference_modal.slim, 03/src/slim/_workshop_modal.slim
やったこと
* モーダルにセッションのレベルを追加
* モーダルにセッションのタグを追加
=> Add session level and tags to modals

03/src/scss/bootstrap.scss
やったこと
* 画面サイズに合わせてロゴサイズが変更するように修正
=> Apply log resize

03/src/slim/_conference.slim, 03/src/slim/index.slim
やったこと
* ScheduleをConferenceにRename
* ついでにWorkshop5となってたところをTBDに変更
* 後日詳細をもらい次第掲載
=> Change schedule to conference

03/src/slim/_registration.slim
やったこと
* Workshopのレジスト用のリンクを追加
* Conferenceの方は（Coming soon）で対応
=> Add Workshop Registration Link

03/src/slim/_registration.slim
やったこと
* Conferenceのレジストレーションリンクの追加
=> Add Conference registration link

03/src/slim/index.slim
やったこと
* ヘッダーのメタ情報にサムネイルの画像情報を追加
=> Add thumbnail info

03/src/slim/_conference.slim, 03/src/slim/_conference_modal.slim
=> Fix speaker name

03/src/slim/_conference.slim, 03/src/slim/_conference_modal.slim
https://ntt-developers.slack.com/archives/C1EABBTEU/p1535412699000100
=> 宮地さんのセッションタイトルを変更

.travis.yml, 01/package.json, 02/package.json
=> update travis-ci settings

05/src/scss/style.scss, 05/src/slm/index.slm
- 下記ページを参考に開催概要を追記
- [Developers Summit 2021（2021.02.18-19）](https://event.shoeisha.jp/devsumi/20210218)
- [CloudNative Days Spring 2021 ONLINE](https://event.cloudnativedays.jp/cndo2021)
=> Add details to about

05/src/scss/style.scss, 05/src/slm/index.slm
- タイムテーブルを追加
- 参考: [NTT Tech Conference #5 - connpass](https://ntt-techconf.connpass.com/event/203831/)
- 講演者の一覧と詳細はアイコンが揃ってから別の Pull Request で追加します
=> Add timetable

05/src/slm/index.slm
~~スマートフォンでアイコンをタップした際に modal 表示後も tooltip が残る問題を修正~~
タッチデバイスで tooltip を表示しないように修正
=> Fix tooltip behavior on mobile devices

05/src/slm/index.slm
=> Add profiles

05/package-lock.json, 05/src/slm/index.slm
下記を参考に各講演の資料をリンク
https://ntt-techconf.connpass.com/event/203831/presentation/
=> Add presentations

2022/src/yaml/data.yaml
- fix: 「Kerberosさんはコミュ障です」の概要分を修正
- fix: 「Kerberosさんはコミュ障です」の準備事項にdetection LabのURLと詳細情報を追記
=> 「Kerberosさんは、コミュ障です」の概要及び準備事項の修正

2022/src/yaml/data.yaml
NRはこれ
- [国内初、「AWS Outposts」に自社データ分析ツールを組み込んだソリューションを開発](https://www.ntt.com/about-us/press-releases/news/article/2022/0314.html)
=> News Release に合わせて発表タイトル、概要等を変更

.github/workflows/deploy-to-github-pages.yml
- Fix: https://github.com/ntt-developers/ntt-tech-conference/actions/runs/7971430396
- Ref: https://github.com/ntt-developers/ntt-tech-conference/commit/8d7ec19e8d13ca08ecf1a00fb935e57d0ade8a4b#diff-ff49704c25d08d294e707839cc3d2831fbf4a6eada505c46b721163df00981ea
=> 🐛 Fix 'Deploy to GitHub Pages' Action

2024/public/images/logo.svg
#282 が fork 先からの PR のため Merge できないため、fork 先から commit を拾って出し直したバージョン
Close: #282
=> fix: 2024: ロゴのXMLエラーを修正

2024/src/yaml/data.yaml
docomo R&D OPEN LAB ODAIBA の分は別途記載してマージ予定
=> Add LT's Title & Speaker

2024/src/yaml/data.yaml
=> Add word to NTT Solmare's title

2025/src/yaml/data.yaml
This pull request includes an update to the `sessions` section in the `2025/src/yaml/data.yaml` file. The change updates the speaker description for 福田裕大 to provide more detailed information about their role and responsibilities at NTTデータ.
* [`2025/src/yaml/data.yaml`](diffhunk://#diff-b9d31888a43e0c14470a68d259ee30a1989647ad582e600aef442d30d6899cc9L238-R238): Updated 福田裕大's speaker description to include details about their involvement in 3D data analysis and image analysis.
=> fix(data): Change speaker description

2025/src/yaml/data.yaml
This pull request includes a change to the `2025/src/yaml/data.yaml` file. The change updates the `session_types` value from "Presentation" to "イベント".
* [`2025/src/yaml/data.yaml`](diffhunk://#diff-b9d31888a43e0c14470a68d259ee30a1989647ad582e600aef442d30d6899cc9L73-R73): Updated the `session_types` value from "Presentation" to "イベント".
=> fix(data): Change registration button name
